# Generated by Django 2.0.3 on 2018-03-30 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_name',
            field=models.CharField(default='update name', max_length=255, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
