# Generated by Django 2.0.1 on 2018-04-02 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0006_auto_20180401_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftpair',
            name='gift_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_receiver', to='secret_santa.Member'),
        ),
    ]
