# Generated by Django 2.0.1 on 2018-04-02 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0007_auto_20180401_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_member',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='list_member',
            name='members',
        ),
        migrations.AlterField(
            model_name='giftpair',
            name='gift_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret_santa.Member'),
        ),
        migrations.DeleteModel(
            name='List_Member',
        ),
    ]
