# Generated by Django 2.1 on 2018-08-09 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa', '0008_auto_20180401_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='telephone',
            field=models.CharField(default='9999999999', max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
